import type { SimAPI, SpecConfig } from '../../engine/types'

/**
 * Arms Warrior — patch 12.1.0 (Midnight, Season 2), Slayer raid single-target
 * build, 2H. Slayer is the recommended raid/ST hero talent in 12.1 across
 * sources ("Slayer is the stronger option right now for patch 12.1" — Maxroll).
 * Sources (verified 2026-08-24):
 * - Wowhead: https://www.wowhead.com/guide/classes/warrior/arms/rotation-cooldowns-pve-dps
 * - Icy Veins: https://www.icy-veins.com/wow/arms-warrior-pve-dps-rotation-cooldowns-abilities
 *   (talent string is Icy Veins' "Arms Single-Target - Slayer" loadout from
 *   https://www.icy-veins.com/wow/arms-warrior-pve-dps-spec-builds-talents)
 * - Method: https://www.method.gg/guides/arms-warrior/playstyle-and-rotation
 * - Maxroll: https://maxroll.gg/wow/class-guides/arms-warrior-raid-guide
 *
 * Resource model: Rage (max 100), generated by slow 2H auto attacks
 * (~15 rage per swing, APPROX). The dummy never leaves 100% HP, so Execute
 * appears only through Slayer's Sudden Death procs (free, usable at any HP).
 * Slayer mechanics modeled: Slayer's Dominance (attacks trigger Slayer's
 * Strike, stacking Marked for Execution ×3, +10% Execute damage each),
 * Imminent Demise (every 3rd Slayer's Strike grants Sudden Death, 2 stacks),
 * Executioner (consuming Sudden Death refunds Bladestorm cooldown — 5s
 * APPROX), Opportunist (Mortal Strike can buff next Overpower +25%, 2 stacks
 * per Icy Veins' "two stacks of Opportunist" condition), Martial Prowess
 * (Overpower stacks amp Mortal Strike), Anger Management (Rage spent refunds
 * Avatar/Bladestorm cooldown, 1s per 20 — APPROX), and the Midnight Apex
 * Heroic Strike proc (replaces Slam, free, high priority — trigger APPROX).
 * S2 tier ("Jade Warlord's Dominion"): 2pc Mortal Strike/Execute +10% (folded
 * into coefficients); 4pc Overpower +15% (folded) and Mortal Strike/Overpower
 * buff the next Slam/Heroic Strike +20%, stacking 5 (modeled, tracked
 * passively per Icy Veins).
 * APPROX-flagged: auto cadence/rage, all proc chances, Slayer's Strike/Heroic
 * Strike coefficients, Bladestorm as scheduled pulses (no movement lock),
 * Imminent Demise Bladestorm bonus strikes unmodeled, Cleave-as-Rend-refresh
 * folded into the Rend button. Damage in AP units.
 */

const AUTO_COEFF = 1.0
const SWING_TIME = 3.6
const SWING_RAGE = 15         // APPROX
const MS_COEFF = 2.86         // 2.6 incl. S2 2pc +10%
const MS_PER_OP = 0.15        // Martial Prowess: +15% per Overpower stack
const OP_COEFF = 1.27         // 1.1 incl. S2 4pc +15%
const OP_PER_OPPORTUNIST = 0.25
const EXEC_COEFF = 2.4        // incl. S2 2pc +10%; Sudden Death cast (free)
const MARKED_AMP = 0.10       // Marked for Execution: +10% Execute per stack
const STRIKE_COEFF = 0.45     // Slayer's Strike (APPROX)
const STRIKE_CHANCE = 0.35    // per auto/MS/OP (APPROX)
const SD_BLADESTORM_REFUND = 5 // Executioner (APPROX)
const CS_COEFF = 1.5
const CS_AMP = 1.30           // Colossus Smash: +30% damage taken
const REND_DIRECT = 0.30
const REND_TICK = 0.26        // per 3s tick
const BLADESTORM_PULSE = 0.55 // ×6
const SLAM_COEFF = 0.85
const HS_COEFF = 1.5          // Apex Heroic Strike proc (APPROX)
const HS_CHANCE = 0.20        // per MS/OP (APPROX)
const SURGE_PER_STACK = 0.20  // S2 4pc: next Slam/HS +20% per stack, max 5
const AVATAR_AMP = 1.20

function csUp(s: SimAPI): boolean {
  return s.auraRemains('target', 'colossus_smash') > 0
}

function hsReady(s: SimAPI): boolean {
  return s.auraRemains('player', 'heroic_strike_ready') > 0
}

/** Anger Management: every 20 Rage spent refunds 1s of Avatar and Bladestorm (APPROX) */
function angerManagement(s: SimAPI, rageSpent: number) {
  s.reduceCooldown('avatar', rageSpent / 20)
  s.reduceCooldown('bladestorm', rageSpent / 20)
}

/** Slayer's Dominance: attacks can trigger Slayer's Strike, stacking Marked
 *  for Execution; every 3rd strike grants Sudden Death (Imminent Demise). */
function rollSlayersStrike(s: SimAPI) {
  if (s.rng('slayers_strike') < STRIKE_CHANCE) {
    s.damage("Slayer's Strike", STRIKE_COEFF)
    s.applyAura('target', 'marked_for_execution', { stacks: 1 })
    s.data.strikeCount = (s.data.strikeCount ?? 0) + 1
    if (s.data.strikeCount >= 3) {
      s.data.strikeCount -= 3
      s.applyAura('player', 'sudden_death', { stacks: 1 })
    }
  }
}

export const armsWarrior: SpecConfig = {
  name: 'Arms Warrior',
  specId: 'warrior-arms',
  specIcon: 'ability_warrior_savageblow',
  resourceName: 'Rage',
  resourceMax: 100,
  startingResource: 0,

  source: {
    guideUrl: 'https://www.wowhead.com/guide/classes/warrior/arms/rotation-cooldowns-pve-dps',
    buildName: 'Slayer Raid Single-Target',
    heroTalent: 'Slayer',
    // Icy Veins "Arms Single-Target - Slayer" loadout (spec-builds-talents page)
    talentString: 'CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmZzMzMzgxMDAAAAgZWmZAhxyyALgBMDTgZwGYmx2YbglZWGgZGAMDDA',
    retrieved: '2026-08-24',
  },

  onCombatStart: (s) => {
    // slow 2H swings; rage per swing is the main income (APPROX)
    const swing = () => {
      s.damage('Auto Attack', AUTO_COEFF)
      s.gain(SWING_RAGE, 'auto')
      rollSlayersStrike(s)
      s.schedule(s.time + SWING_TIME * s.hasteMult(), swing)
    }
    s.schedule(s.time + 0.1, swing)
  },

  auras: [
    { id: 'overpower', name: 'Overpower', icon: 'ability_meleedamage', duration: 15, maxStacks: 2 },
    { id: 'opportunist', name: 'Opportunist', icon: 'ability_criticalstrike', duration: 12, maxStacks: 2 },
    { id: 'colossus_smash', name: 'Colossus Smash', icon: 'ability_warrior_colossussmash', duration: 10, debuff: true },
    { id: 'avatar', name: 'Avatar', icon: 'warrior_talent_icon_avatar', duration: 20 },
    { id: 'sudden_death', name: 'Sudden Death', icon: 'ability_warrior_improveddisciplines', duration: 10, maxStacks: 2 },
    { id: 'marked_for_execution', name: 'Marked for Execution', icon: 'ability_blackhand_marked4death', duration: 20, maxStacks: 3, debuff: true },
    { id: 'slam_surge', name: "Warlord's Surge", icon: 'ability_warrior_endlessrage', duration: 15, maxStacks: 5 },
    { id: 'heroic_strike_ready', name: 'Heroic Strike!', icon: 'ability_rogue_ambush', duration: 12 },
    {
      id: 'rend', name: 'Rend', icon: 'ability_gouge', duration: 15, pandemic: true, debuff: true,
      tick: { interval: 3, hasted: true, onTick: s => s.damage('rend', REND_TICK) },
    },
  ],

  abilities: [
    {
      id: 'mortal_strike',
      name: 'Mortal Strike',
      icon: 'ability_warrior_savageblow',
      spellId: 12294,
      cost: 30,
      cooldown: 6,
      onResolve: (s) => {
        const stacks = s.stacks('player', 'overpower')
        if (stacks > 0) s.removeAura('player', 'overpower')
        s.damage('mortal_strike', MS_COEFF * (1 + MS_PER_OP * stacks))
        s.applyAura('player', 'slam_surge', { stacks: 1 }) // S2 4pc
        if (s.rng('opportunist') < 0.4) s.applyAura('player', 'opportunist', { stacks: 1 })
        if (s.rng('hs_proc') < HS_CHANCE) s.applyAura('player', 'heroic_strike_ready')
        rollSlayersStrike(s)
        angerManagement(s, 30)
      },
    },
    {
      id: 'overpower',
      name: 'Overpower',
      icon: 'ability_meleedamage',
      spellId: 7384,
      cooldown: 12,
      charges: 2,
      onResolve: (s) => {
        const opp = s.stacks('player', 'opportunist')
        if (opp > 0) s.removeAura('player', 'opportunist')
        s.damage('overpower', OP_COEFF * (1 + OP_PER_OPPORTUNIST * opp))
        s.applyAura('player', 'overpower', { stacks: 1 })
        s.applyAura('player', 'slam_surge', { stacks: 1 }) // S2 4pc
        if (s.rng('hs_proc') < HS_CHANCE) s.applyAura('player', 'heroic_strike_ready')
        rollSlayersStrike(s)
      },
    },
    {
      id: 'rend',
      name: 'Rend',
      icon: 'ability_gouge',
      spellId: 772,
      cost: 20,
      onResolve: (s) => {
        s.damage('rend', REND_DIRECT)
        s.applyAura('target', 'rend')
        angerManagement(s, 20)
      },
    },
    {
      // Sudden Death proc cast only — the dummy never leaves 100% HP
      id: 'execute',
      name: 'Execute',
      icon: 'inv_sword_48',
      spellId: 163201,
      usable: (s) => s.stacks('player', 'sudden_death') > 0 || 'requires Sudden Death',
      onResolve: (s) => {
        const marked = s.stacks('target', 'marked_for_execution')
        if (marked > 0) s.removeAura('target', 'marked_for_execution')
        s.damage('execute', EXEC_COEFF * (1 + MARKED_AMP * marked))
        s.consumeStack('player', 'sudden_death')
        s.reduceCooldown('bladestorm', SD_BLADESTORM_REFUND) // Executioner
      },
    },
    {
      id: 'colossus_smash',
      name: 'Colossus Smash',
      icon: 'ability_warrior_colossussmash',
      spellId: 167105,
      cooldown: 45,
      onResolve: (s) => {
        s.damage('colossus_smash', CS_COEFF)
        s.applyAura('target', 'colossus_smash')
      },
    },
    {
      id: 'bladestorm',
      name: 'Bladestorm',
      icon: 'ability_warrior_bladestorm',
      spellId: 227847,
      cooldown: 90,
      onResolve: (s) => {
        for (let i = 0; i < 6; i++) {
          s.schedule(s.time + 0.5 * i, () => s.damage('bladestorm', BLADESTORM_PULSE))
        }
      },
    },
    {
      // One button, as in game: the Apex Heroic Strike proc replaces Slam.
      id: 'slam',
      name: 'Slam',
      icon: 'ability_warrior_decisivestrike',
      spellId: 1464,
      displayName: (s) => (hsReady(s) ? 'Heroic Strike' : 'Slam'),
      displayIcon: (s) => (hsReady(s) ? 'ability_rogue_ambush' : 'ability_warrior_decisivestrike'),
      cost: 20,
      costMod: (s) => (hsReady(s) ? 0 : 20),
      onResolve: (s) => {
        const surge = s.stacks('player', 'slam_surge')
        if (surge > 0) s.removeAura('player', 'slam_surge')
        const mult = 1 + SURGE_PER_STACK * surge // S2 4pc
        if (hsReady(s)) {
          s.removeAura('player', 'heroic_strike_ready')
          s.damage('heroic_strike', HS_COEFF * mult)
        } else {
          s.damage('slam', SLAM_COEFF * mult)
          rollSlayersStrike(s)
          angerManagement(s, 20)
        }
      },
    },
    {
      id: 'avatar',
      name: 'Avatar',
      icon: 'warrior_talent_icon_avatar',
      spellId: 107574,
      cooldown: 90,
      offGcd: true,
      onResolve: (s) => s.applyAura('player', 'avatar'),
    },
  ],

  actionBar: [
    'mortal_strike', 'overpower', 'rend', 'slam', 'execute',
    'colossus_smash', 'bladestorm', 'avatar',
  ],

  damageMult: (s) => {
    let m = 1
    if (csUp(s)) m *= CS_AMP
    if (s.auraRemains('player', 'avatar') > 0) m *= AVATAR_AMP
    return m
  },

  glows: (s, id) => {
    switch (id) {
      case 'mortal_strike': return s.stacks('player', 'overpower') === 2
      case 'rend': return s.auraRemains('target', 'rend') < 4.5
      case 'execute': return s.stacks('player', 'sudden_death') > 0
      case 'slam': return hsReady(s) || s.stacks('player', 'slam_surge') === 5
      case 'overpower': return s.stacks('player', 'opportunist') === 2
      default: return false
    }
  },

  // shown in the UI; rows mirror `policy` below, in the same order
  priorityList: [
    { abilityId: 'avatar', text: 'Off-GCD, on cooldown (Anger Management brings it back fast)', when: s => s.cooldownRemains('avatar') === 0 },
    { abilityId: 'colossus_smash', text: 'On cooldown — everything hits +30% inside it', when: s => s.cooldownRemains('colossus_smash') === 0 },
    { abilityId: 'rend', text: 'Refresh in the pandemic window (<4.5s left)' },
    { abilityId: 'slam', label: 'Heroic Strike', icon: 'ability_rogue_ambush', text: 'Free Apex proc — press before spending Rage', when: s => hsReady(s) },
    { abilityId: 'execute', text: 'At 2 Sudden Death stacks — never overcap procs', when: s => s.stacks('player', 'sudden_death') >= 2 },
    { abilityId: 'bladestorm', text: 'Inside Colossus Smash (Sudden Death Executes refund it)', when: s => s.cooldownRemains('bladestorm') === 0 && csUp(s) },
    { abilityId: 'overpower', text: 'With 2 Opportunist stacks (+50% Overpower)', when: s => s.stacks('player', 'opportunist') === 2 && s.chargesOf('overpower') > 0 },
    { abilityId: 'mortal_strike', text: 'On cooldown — ideally with 2 Overpower stacks' },
    { abilityId: 'execute', text: 'Spend single Sudden Death procs (eats Marked for Execution)', when: s => s.stacks('player', 'sudden_death') > 0 },
    { abilityId: 'overpower', text: 'Free — stack it for Mortal Strike, never cap charges' },
    { abilityId: 'slam', text: 'Dump Rage above 60 — never cap' },
  ],

  /**
   * Oracle — Wowhead/Icy Veins/Method 12.1 Slayer ST priority, distilled to
   * this kit (Cleave-refresh folded into Rend; Execute exists only through
   * Sudden Death on the full-HP dummy).
   */
  policy: (s) => {
    const rage = s.insanity
    const sd = s.stacks('player', 'sudden_death')
    const rendRemains = s.auraRemains('target', 'rend')

    if (s.cooldownRemains('avatar') === 0) return 'avatar'
    if (s.cooldownRemains('colossus_smash') === 0) return 'colossus_smash'
    if (rendRemains < 4.5 && rage >= 20) return 'rend'
    if (hsReady(s)) return 'slam' // Heroic Strike proc
    if (sd >= 2) return 'execute'
    if (s.cooldownRemains('bladestorm') === 0 && (csUp(s) || s.cooldownRemains('colossus_smash') > 15)) return 'bladestorm'
    if (s.stacks('player', 'opportunist') === 2 && s.chargesOf('overpower') > 0) return 'overpower'
    if (s.cooldownRemains('mortal_strike') === 0 && rage >= 30) return 'mortal_strike'
    if (sd >= 1) return 'execute'
    if (s.chargesOf('overpower') > 0) return 'overpower'
    if (rage >= 60) return 'slam'
    return null
  },

  equivalentChoices: (_s, pressed, oracle) => {
    const fillers = ['overpower', 'slam']
    const heavyHits = ['mortal_strike', 'execute']
    const sets = [fillers, heavyHits]
    return sets.some(set => set.includes(pressed) && set.includes(oracle))
  },
}
