import type { SimAPI, SpecConfig } from '../../engine/types'

/**
 * Arms Warrior — patch 12.1.0 (Midnight, Season 2), Colossus raid ST build
 * (Icy Veins default), 2H. Built from the simc `midnight` APL/source and
 * Icy Veins/Wowhead 12.1 guides.
 *
 * Resource model: Rage (max 100), generated by slow 2H auto attacks
 * (~15 rage per swing, APPROX) plus Skullsplitter and the S2 4pc on
 * Colossus Smash. Execute is excluded — the training dummy never leaves
 * 100% HP (same convention as Shadow Priest's Deathspeaker).
 * Talent assumptions: Martial Prowess (Overpower stacks amp Mortal Strike),
 * Colossus hero tree (Demolish, modeled as 3 scheduled hits instead of the
 * in-game channel lock — APPROX), Apex: Titanic Rupture 3/3 (Demolish
 * extends Colossus Smash 3s). S2 tier: 2pc Overpower +25% (folded into the
 * coefficient); 4pc Colossus Smash grants 20 Rage.
 * APPROX-flagged: auto cadence/rage, Bladestorm modeled as scheduled pulses
 * (no movement lock). Damage in AP units.
 */

const AUTO_COEFF = 1.0
const SWING_TIME = 3.6
const SWING_RAGE = 15        // APPROX
const MS_COEFF = 2.6
const MS_PER_OP = 0.15       // Martial Prowess: +15% per Overpower stack
const OP_COEFF = 1.1         // incl. S2 2pc +25%
const CS_COEFF = 1.5
const CS_AMP = 1.30          // Colossus Smash: +30% damage taken
const REND_DIRECT = 0.30
const REND_TICK = 0.26       // per 3s tick
const SKULL_COEFF = 0.9
const SKULL_RAGE = 20
const DEMOLISH_HIT = 1.2     // ×3
const BLADESTORM_PULSE = 0.55 // ×6
const SLAM_COEFF = 0.85
const AVATAR_AMP = 1.20

function csUp(s: SimAPI): boolean {
  return s.auraRemains('target', 'colossus_smash') > 0
}

export const armsWarrior: SpecConfig = {
  name: 'Arms Warrior',
  specId: 'warrior-arms',
  specIcon: 'ability_warrior_savageblow',
  resourceName: 'Rage',
  resourceMax: 100,
  startingResource: 0,

  onCombatStart: (s) => {
    // slow 2H swings; rage per swing is the main income (APPROX)
    const swing = () => {
      s.damage('Auto Attack', AUTO_COEFF)
      s.gain(SWING_RAGE, 'auto')
      s.schedule(s.time + SWING_TIME * s.hasteMult(), swing)
    }
    s.schedule(s.time + 0.1, swing)
  },

  auras: [
    { id: 'overpower', name: 'Overpower', icon: 'ability_meleedamage', duration: 15, maxStacks: 2 },
    { id: 'colossus_smash', name: 'Colossus Smash', icon: 'ability_warrior_colossussmash', duration: 10, debuff: true },
    { id: 'avatar', name: 'Avatar', icon: 'warrior_talent_icon_avatar', duration: 20 },
    {
      id: 'rend', name: 'Rend', icon: 'ability_gouge', duration: 15, pandemic: true, debuff: true,
      tick: { interval: 3, hasted: true, onTick: s => s.damage('rend', REND_TICK) },
    },
  ],

  abilities: [
    {
      id: 'mortal_strike',
      name: 'Mortal Strike',
      icon: 'ability_warrior_savageblow',
      spellId: 12294,
      cost: 30,
      cooldown: 6,
      onResolve: (s) => {
        const stacks = s.stacks('player', 'overpower')
        if (stacks > 0) s.removeAura('player', 'overpower')
        s.damage('mortal_strike', MS_COEFF * (1 + MS_PER_OP * stacks))
      },
    },
    {
      id: 'overpower',
      name: 'Overpower',
      icon: 'ability_meleedamage',
      spellId: 7384,
      cooldown: 12,
      charges: 2,
      onResolve: (s) => {
        s.damage('overpower', OP_COEFF)
        s.applyAura('player', 'overpower', { stacks: 1 })
      },
    },
    {
      id: 'rend',
      name: 'Rend',
      icon: 'ability_gouge',
      spellId: 772,
      cost: 20,
      onResolve: (s) => {
        s.damage('rend', REND_DIRECT)
        s.applyAura('target', 'rend')
      },
    },
    {
      id: 'colossus_smash',
      name: 'Colossus Smash',
      icon: 'ability_warrior_colossussmash',
      spellId: 167105,
      cooldown: 45,
      onResolve: (s) => {
        s.damage('colossus_smash', CS_COEFF)
        s.applyAura('target', 'colossus_smash')
        s.gain(20, 'cs_4pc') // S2 4pc
      },
    },
    {
      id: 'skullsplitter',
      name: 'Skullsplitter',
      icon: 'inv_skullsplitter',
      spellId: 260643,
      cooldown: 21,
      onResolve: (s) => {
        s.damage('skullsplitter', SKULL_COEFF)
        s.gain(SKULL_RAGE, 'skullsplitter')
      },
    },
    {
      // Colossus capstone: in-game a short channel; modeled as 3 staggered hits
      id: 'demolish',
      name: 'Demolish',
      icon: 'inv_ability_colossuswarrior_demolish',
      spellId: 436358,
      cooldown: 45,
      onResolve: (s) => {
        for (let i = 0; i < 3; i++) {
          s.schedule(s.time + i * 0.6, () => s.damage('demolish', DEMOLISH_HIT))
        }
        // Apex: Titanic Rupture — Demolish extends Colossus Smash 3s
        if (csUp(s)) s.extendAura('target', 'colossus_smash', 3)
      },
    },
    {
      id: 'bladestorm',
      name: 'Bladestorm',
      icon: 'ability_warrior_bladestorm',
      spellId: 227847,
      cooldown: 90,
      onResolve: (s) => {
        for (let i = 0; i < 6; i++) {
          s.schedule(s.time + 0.5 * i, () => s.damage('bladestorm', BLADESTORM_PULSE))
        }
      },
    },
    {
      id: 'slam',
      name: 'Slam',
      icon: 'ability_warrior_decisivestrike',
      spellId: 1464,
      cost: 20,
      onResolve: (s) => s.damage('slam', SLAM_COEFF),
    },
    {
      id: 'avatar',
      name: 'Avatar',
      icon: 'warrior_talent_icon_avatar',
      spellId: 107574,
      cooldown: 90,
      offGcd: true,
      onResolve: (s) => s.applyAura('player', 'avatar'),
    },
  ],

  actionBar: [
    'mortal_strike', 'overpower', 'rend', 'slam', 'colossus_smash',
    'skullsplitter', 'demolish', 'bladestorm', 'avatar',
  ],

  damageMult: (s) => {
    let m = 1
    if (csUp(s)) m *= CS_AMP
    if (s.auraRemains('player', 'avatar') > 0) m *= AVATAR_AMP
    return m
  },

  glows: (s, id) => {
    switch (id) {
      case 'mortal_strike': return s.stacks('player', 'overpower') === 2
      case 'rend': return s.auraRemains('target', 'rend') < 4.5
      case 'skullsplitter': return s.insanity < 40
      default: return false
    }
  },

  priorityList: [
    { abilityId: 'avatar', text: 'Off-GCD, on cooldown with Colossus Smash', when: s => s.cooldownRemains('avatar') === 0 },
    { abilityId: 'colossus_smash', text: 'On cooldown — everything hits +30% inside it', when: s => s.cooldownRemains('colossus_smash') === 0 },
    { abilityId: 'rend', text: 'Refresh in the pandemic window (<4.5s left)' },
    { abilityId: 'demolish', text: 'Inside Colossus Smash (extends it — Apex)', when: s => s.cooldownRemains('demolish') === 0 && s.auraRemains('target', 'colossus_smash') > 0 },
    { abilityId: 'bladestorm', text: 'Inside Colossus Smash', when: s => s.cooldownRemains('bladestorm') === 0 && s.auraRemains('target', 'colossus_smash') > 0 },
    { abilityId: 'mortal_strike', text: 'On cooldown — ideally with 2 Overpower stacks' },
    { abilityId: 'skullsplitter', text: 'When Rage-starved (<60)', when: s => s.cooldownRemains('skullsplitter') === 0 && s.insanity < 60 },
    { abilityId: 'overpower', text: 'Free — stack it for Mortal Strike, never cap charges' },
    { abilityId: 'slam', text: 'Dump Rage above 60 — never cap' },
  ],

  policy: (s) => {
    const rage = s.insanity
    const rendRemains = s.auraRemains('target', 'rend')

    if (s.cooldownRemains('avatar') === 0) return 'avatar'
    if (s.cooldownRemains('colossus_smash') === 0) return 'colossus_smash'
    if (rendRemains < 4.5 && rage >= 20) return 'rend'
    if (s.cooldownRemains('demolish') === 0 && (csUp(s) || s.cooldownRemains('colossus_smash') > 15)) return 'demolish'
    if (s.cooldownRemains('bladestorm') === 0 && (csUp(s) || s.cooldownRemains('colossus_smash') > 15)) return 'bladestorm'
    if (s.cooldownRemains('mortal_strike') === 0 && rage >= 30) return 'mortal_strike'
    if (s.cooldownRemains('skullsplitter') === 0 && rage < 60) return 'skullsplitter'
    if (s.chargesOf('overpower') > 0) return 'overpower'
    if (rage >= 60) return 'slam'
    return null
  },

  equivalentChoices: (_s, pressed, oracle) => {
    const fillers = ['overpower', 'slam']
    const csWindow = ['demolish', 'bladestorm']
    const sets = [fillers, csWindow]
    return sets.some(set => set.includes(pressed) && set.includes(oracle))
  },
}
